In [3]:
import numpy as np
import time

In [6]:
#Execution performance
size = 100_000_000

#Python list
py_list = list(range(size))
start = time.time()
sq_arr = [i**2 for i in py_list]
end = time.time()
print(f"Python list time = {end-start} seconds")

#Numpy array
np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f"Numpy array time = {end-start} seconds")

Python list time = 6.436179161071777 seconds
Numpy array time = 1.0643975734710693 seconds


In [8]:
#memory
import sys

#python list memory
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

#np arr memory
print(f"np arr size = {np_arr.nbytes} bytes")


python list size = 80000005600000000 bytes
np arr size = 800000000 bytes


In [19]:
#creating np array
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1,2,3,4,5,"Syed"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

#2d-array
arr_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2D, arr_2D.dtype, arr_2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'Syed'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 (3, 3)


In [31]:
#creating np_arr using numpy inbuilt functions
arr1 = np.zeros((2,3), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((3,3)) #prefill
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100) #prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3) #evenly spaced arr
print(arr6, arr6.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [37]:
#array properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #dimension m x n
print(arr.size) #tot els - 9
print(arr.dtype) #int64
print(arr.ndim) #2D-arr

#type conversion of data type in numpy
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [39]:
#Operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

#reshape
reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


AttributeError: 'numpy.ndarray' object has no attribute 'reshap'